### PR TITLE
[RFR] Make it works at first install

### LINKED ISSUE #133: make build-admin ERROR in ./~/admin-on-rest/lib/mui/input/RichTextInput.css
```
$ node --version
v6.9.1

$ npm --version
3.10.8

$ make build-admin
Building frontend application
Hash: aa014ab78b65d19d7bc2                                                                
Version: webpack 2.1.0-beta.25
Time: 10042ms
     Asset       Size  Chunks             Chunk Names
  index.js    9.33 MB       0  [emitted]  index
index.html  398 bytes          [emitted]  
[1131] multi index 28 bytes {0} [built]
    + 1131 hidden modules

ERROR in ./~/admin-on-rest/lib/mui/input/RichTextInput.js
Module not found: Error: Can't resolve 'quill' in '.../javascript-boilerplate/node_modules/admin-on-rest/lib/mui/input'
 @ ./~/admin-on-rest/lib/mui/input/RichTextInput.js 31:13-29
 @ ./~/admin-on-rest/lib/mui/input/index.js
 @ ./~/admin-on-rest/lib/mui/index.js
 @ ./src/admin/js/Admin.js
 @ ./src/admin/js/main.js
 @ multi index

ERROR in ./~/admin-on-rest/lib/mui/input/RichTextInput.css
Module parse failed: .../javascript-boilerplate/node_modules/admin-on-rest/lib/mui/input/RichTextInput.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "~quill/dist/quill.snow.css";
| 
| .ql-editor {
 @ ./~/admin-on-rest/lib/mui/input/RichTextInput.js 37:0-30
 @ ./~/admin-on-rest/lib/mui/input/index.js
 @ ./~/admin-on-rest/lib/mui/index.js
 @ ./src/admin/js/Admin.js
 @ ./src/admin/js/main.js
 @ multi index
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
make: *** [build-admin] Error 2

```

### PR DESCRIPTION
**Pull request by Kmaschta**
- Admin did not works at first install (`quill` was not installed and it missed a css loader for it) Fix #133
- There was an ugly margin around the admin
- An error was threw if the admin credentials was incorrect (there no error then but still no error message)
- The README was out of date

### CODE REVIEW

File: src/admin/js/user/sagas.js [hunk 1]
```diff
@@ -23,7 +23,11 @@ export const getUserFromToken = (token) => {
 
 export const signIn = (fetchSaga, storeLocalUser) => function* signInSaga({ payload: { previousRoute, ...payload } }) {
     const { error, result } = yield call(fetchSaga, { payload });
-    const user = yield call(getUserFromToken, result.token);
+
+    let user = {};
+    if (result) {
+        user = yield call(getUserFromToken, result.token);
```
Comment (djhi) [inline src/admin/js/user/sagas.js]: You can put this line directly after the error check with const

**Comment by Kmaschta** [comment]
@djhi Done and green!
